# Generated by Django 5.0 on 2024-08-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_nel_passphrase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chi_PassPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.TextField(max_length=500, unique=True)),
                ('amount_of_pi', models.CharField(blank=True, max_length=100, null=True)),
                ('unlock_date', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('look_up', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Chi Keys',
                'verbose_name_plural': 'Chi Keys',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Santus_PassPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.TextField(max_length=500, unique=True)),
                ('amount_of_pi', models.CharField(blank=True, max_length=100, null=True)),
                ('unlock_date', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('look_up', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Santus Keys',
                'verbose_name_plural': 'Santus Keys',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='nel_passphrase',
            options={'ordering': ['-date'], 'verbose_name': 'Nel Keys', 'verbose_name_plural': 'Nel Keys'},
        ),
    ]
